# Generated by Django 2.2.9 on 2021-12-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211124_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст нового поста')),
                ('group', models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться пост', on_delete=django.db.models.deletion.CASCADE, to='posts.Group')),
            ],
        ),
    ]
