# Generated by Django 2.2.16 on 2022-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220122_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Человекочитаемая часть адреса'),
        ),
    ]
